# Generated by Django 5.1 on 2024-08-28 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapi', '0002_alter_menuitem_options_featuredmenuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='photo',
            new_name='photo_url',
        ),
    ]
